.\" Copyright (C) 2008 SUSE Linux Products GmbH
.\"
.\" This program is free software; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License
.\" as published by the Free Software Foundation; either version 2
.\" of the License, or (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program; if not, write to the Free Software
.\" Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307,
.\" USA.
.\"
.\" This file is kept in the following git repository:
.\"
.\" git://git.kernel.org/pub/scm/linux/kernel/git/hare/mkinitrd.git
.\"
.TH lsinitrd 8
.SH NAME
lsinitrd \- lists contents of an initrd disk image
.SH SYNOPSIS
\fBlsinitrd\fR [options] [initrd file]
.SH DESCRIPTION
\fBlsinitrd\fR list the contents of an initial ramdisk images
for booting Linux as created by \fBmkinitrd\fR.

.SH OPTIONS
.TP
\fB-h\fR
This Text.
.TP
\fB-l\fR
verbose listing, similar to \fBls -l\fR.

.BR 
.SH AUTHORS
Hannes Reinecke <hare@suse.de>, Alexander Graf <agraf@suse.de>
.BR 
