#!/bin/bash
#
# Build a mkinitrd source rpm 
#

DESTDIR="/tmp/mkinitrd"

while [ $# -gt 0 ] ; do
    case "$1" in
	-d)
	    DESTDIR=$2;
	    shift 2;
	    ;;
	--destdir)
	    DESTDIR=${$1#*=};
	    shift;
	    ;;
	-r)
	    RELEASE=$2;
	    shift 2;
	    ;;
	--release=)
	    RELEASE=${1##*=};
	    shift;
	    ;;
	-f|--force)
	    force=1;
	    shift;
	    ;;
	*)
	    echo "Usage: build_rpm [-f] [-d dir|--destdir=DIR] [-b BRANCH|--branch=BRANCH]"
	    exit 1;
	    ;;
    esac
done

if ! which git-archive > /dev/null ; then
    echo "git-archive not found, cannot continue"
    exit 1
fi

if [ -z "$RELEASE" ] ; then
    RELEASE="sles10"
    echo "Release is not set, checking out from $RELEASE"
fi

if [ -d "$DESTDIR" ] ; then
    if [ -z "$force" ] ; then
	echo "directory $DESTDIR exists, cannot continue"
	exit 1
    else
	if ! rm -rf "$DESTDIR" ; then
	    echo "Cannot remove directory $DESTDIR"
	    exit 1
	fi
    fi
fi

rel=$(echo $RELEASE | tr [:lower:] [:upper:])

case $rel in
    SLES9*)
	echo "Checking out for SLES9"
	BRANCH=SLES9_BRANCH
	;;
    SLES10*)
	echo "Checking out for SLES10"
	BRANCH=SLES10_BRANCH
	;;
    *)
	echo "Unknown release $RELEASE, cannot continue"
	exit 1
	;;
esac

if ! git branch | grep -q "$BRANCH" ; then
    echo "Branch \"$BRANCH\" does not exist"
    exit 1
fi

if ! mkdir $DESTDIR ; then
    echo "Cannot create directory $DESTDIR"
    exit 1
fi

git archive --format=tar "$BRANCH" > $DESTDIR/mkinitrd.tar
(cd $DESTDIR; tar xf mkinitrd.tar; rm -f mkinitrd.tar; rm -rf bonked; rm -f build_rpm)

echo "mkinitrd src rpm copied to $DESTDIR"
