#!/bin/bash
#
# Build a mkinitrd source rpm 
#

DESTDIR="/tmp/mkinitrd"

while [ $# -gt 0 ] ; do
    case "$1" in
	-d)
	    DESTDIR=$2;
	    shift 2;
	    ;;
	--destdir)
	    DESTDIR=${$1#*=};
	    shift;
	    ;;
	-b)
	    BRANCH=$2;
	    shift 2;
	    ;;
	--branch=)
	    BRANCH=${1##*=};
	    shift;
	    ;;
	-f|--force)
	    force=1;
	    shift;
	    ;;
	*)
	    echo "Usage: build_rpm [-f] [-d dir|--destdir=DIR] [-b BRANCH|--branch=BRANCH]"
	    exit 1;
	    ;;
    esac
done

VERSION=$(sed -n 's/Version: *\(.*\)/\1/p' mkinitrd.spec)

if ! which git-archive > /dev/null ; then
    echo "git-archive not found, cannot continue"
    exit 1
fi

if [ -z "$BRANCH" ] ; then
    BRANCH="master"
    echo "Branch is not set, checking out from $BRANCH"
fi

if [ -d "$DESTDIR" ] ; then
    if [ -z "$force" ] ; then
	echo "directory $DESTDIR exists, cannot continue"
	exit 1
    else
	if ! rm -rf "$DESTDIR" ; then
	    echo "Cannot remove directory $DESTDIR"
	    exit 1
	fi
    fi
fi

if ! git branch | grep -q "$BRANCH" ; then
    echo "Branch \"$BRANCH\" does not exist"
    exit 1
else
    echo "Checking out from $BRANCH"
fi

if ! mkdir $DESTDIR ; then
    echo "Cannot create directory $DESTDIR"
    exit 1
fi

git archive --format=tar --prefix=mkinitrd-$VERSION/ "$BRANCH" \
    | gzip > $DESTDIR/mkinitrd.tgz

cp mkinitrd.spec $DESTDIR
cp mkinitrd.changes $DESTDIR

echo "mkinitrd src rpm copied to $DESTDIR"
