.\" Copyright (C) 2003 SuSE Linux AG
.\"$Id: mkinitrd.8,v 1.1.4.2 2006/01/18 09:52:10 hare Exp $
.TH mkinitrd 8
.SH NAME
mkinitrd, mk_initrd \- create initrd disk image
.SH SYNOPSIS
\fBmkinitrd\fR [options] [root_dir]
.SH DESCRIPTION
\fBmkinitrd\fR creates initial ramdisk images for booting linux
         with enviroments which need loading modules 
         before mounting the root device (e.g SCSI 
         controller)
.SH OPTIONS
.TP
\fB-h\fR
This Text.
.TP
\fB-k  "kernel list"\fR
list of kernel images for which initrd files are created (relative to
boot_dir), defaults to "vmlinuz vmlinuz.shipped"
.TP
\fB-i "initrd list"\fR 
list of file names (relativ to boot_dir) for the initrd; positions have to
match the "kernel list",  defaults to "initrd initrd.shipped"
.TP
\fB-m "module list"\fR 
modules to include in initrd, defaults to INITRD_MODULES variable in
/etc/sysconfig/kernel 
.TP
\fB-n inode_number\fR 
number of inodes for the initrd, defaults to 4096.
.TP
\fB-b boot_dir\fR
boot dir, defaults to "/boot", where the initrd is created.
.TP
\fB-d root_device\fR
root device, defaults to the device from which the root_dir is mounted; 
overwrites the rootdev enviroment variable if set
.TP
\fB-s size\fR       
Add splash animation and bootscreen to initrd.
.TP
\fB-D iface\fR       
Enable DHCP configuration on interface
\fIiface\fR
.TP
\fB-I iface\fR
Enable static configuration on interface
\fIiface\fR
.TP
\fB-a acpi_dsdt\fR
Attach compiled ACPI DSDT (Differentiated System Description Table)
to initrd. This replaces the DSDT of the BIOS. Defaults to the ACPI_DSDT
variable in /etc/sysconfig/kernel.
.TP
\fB-S\fR       
Load policy file for SELinux if exists.
.TP
\fB-t tmp_dir\fR 
tmp dir, defaults to "/tmp".
.TP
\fB-x size\fR 
additional space in kBytes on the initrd, default is 2048.
.TP
\fBroot_dir\fR
the directory the root partition is mounted to defaults to "/"

.SH NOTE
\fBmk_initrd\fR is now a symbolic link to \fBmkinitrd\fR.
.SH ENVIRONMENT VARIABLES
You can specify the root device via the environment variable rootdev (e.g.
"rootdev=/dev/hda mk_initrd").
.BR 
.SH "SEE ALSO"
.BR \fBinitrd\fR(4)
.SH AUTHOR
Steffen Winterfeldt <wfeldt@suse.de>, Susanne Oberhauser
<froh@suse.de>, Hannes Reinecke <hare@suse.de>
.BR 
